name: Flatten Content from Obsidian to Garden Repo

on:
  push:
    branches:
      - main

jobs:
  flatten-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Garden Repo with Submodule
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules are initialized and updated

      - name: Debug Check Current Directory
        run: pwd

      - name: Debug List Files in Current Directory
        run: ls -la

      - name: add the token to .gitsubmodules
        env: ${{ GH_TOKEN }}
        run: |
          git config submodule.obsidian.url obsidian https://${GH_TOKEN}@github.com/larralapid/obsidian.git
          git submodule sync
          echo "added ghtoken" 
          
      - name: Copy Obsidian Content to Garden
        run: |
          echo "Ensuring content directory is fresh..."
          rm -rf content  # Remove existing content directory if it exists
          mkdir content   # Create a new content directory
          echo "Copying files from submodule 'obsidian' to 'content'..."
          cp -r obsidian/* content/  # Copy all files and directories from obsidian to content
          echo "Submodule files successfully copied."

      - name: Debug List Files in Content Directory
        run: ls -la content  # Verify the content directory is populated

      - name: Commit and Push Flattened Content
        run: |
          git config --global user.name "larralapid"
          git config --global user.email "larralapid@gmail.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Flattened content from Obsidian vault"
            git push origin main
          fi
