name: Flatten Submodule and Push to Garden Repo

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  flatten-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Flatten submodule content
        run: |
          rm -rf content
          cp -r content/* ./

      - name: Commit and push flattened content
        run: |
          git config --global user.name "larralapid"
          git config --global user.email "larralapid@gmail.com"
          git add .
          git commit -m "Flattened content from obsidian submodule"
          git push origin main
