name: Flatten Content from Obsidian to Garden Repo

on:
  push:
    branches:
      - main  # Trigger when a push happens to the main branch in the Garden repo

jobs:
  flatten-content:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Garden repo (no submodule)
      - name: Checkout Garden Repo
        uses: actions/checkout@v3

      # Step 2: Overwrite content directory in Garden repo with Obsidian files
      - name: Copy Obsidian content to Garden
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          rm -rf content  # Remove old content directory
          git clone https://$GH_TOKEN@github.com/larralapid/obsidian.git content

      # Step 3: Commit and push the updated content to the Garden repo
      - name: Commit and push flattened content
        run: |
          git config --global user.name "larralapid"
          git config --global user.email "larralapid@gmail.com"
          git add .
          git commit -m "Flattened content from Obsidian vault"
          git push origin main  # Push to the main branch in the Garden repo
