name: Flatten Content from Obsidian to Garden Repo

on:
  push:
    branches:
      - main

jobs:
  flatten-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Garden Repo
        uses: actions/checkout@v3

      - name: Debug Check current directory
        run: pwd

      - name: Debug List files in current directory
        run: ls -la

      - name: Copy Obsidian content to Garden
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Removing old content directory..."
          rm -rf content
          echo "Cloning Obsidian repository..."
          git clone https://$GH_TOKEN@github.com/larralapid/obsidian.git content
          echo "Cloning completed."

      - name: Debug: List files after clone
        run: ls -la

      - name: Commit and push flattened content
        run: |
          git config --global user.name "larralapid"
          git config --global user.email "larralapid@gmail.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Flattened content from Obsidian vault"
            git push origin main
