name: Flatten Submodule and Push to Garden Repo

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  flatten-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Create temporary branch
        run: |
          git checkout -b temp-branch

      - name: Flatten submodule content
        run: |
          mkdir -p content
          cp -r content-copy/* content
          rm -rf content-copy

      - name: Commit and push flattened content
        run: |
          git config --global user.name "larralapid"
          git config --global user.email "larralapid@gmail.com"
          git add .
          git commit -m "Flattened content from obsidian submodule"
          git push origin temp-branch

      - name: Merge temporary branch into main
        run: |
          git checkout main
          git merge temp-branch
          git push origin main
